function definitions = getPreferenceDefinitions()
%getPreferenceDefinitions - Name, default and validation of each preference
%   definitions = ebrains.internal.getPreferenceDefinitions() returns a
%   struct array with one element per preference and the fields:
%       Name          - Name of the preference and of its setting
%       FactoryValue  - Default value of the preference
%       ValidationFcn - Handle to the named function that validates a
%                       value of the setting
%
%   ebrains.internal.createFactoryTree builds the settings from these, and
%   ebrains.util.Preferences reads the defaults from them when the
%   settings are not loaded. Add a preference here and as a property of
%   ebrains.util.Preferences.
%
%   See also ebrains.internal.createFactoryTree, ebrains.util.Preferences

    definitions = [ ...
        struct( ...
            "Name", "AutoLogin", ...
            "FactoryValue", false, ...
            "ValidationFcn", @matlab.settings.mustBeLogicalScalar), ...
        struct( ...
            "Name", "AutoRenew", ...
            "FactoryValue", true, ...
            "ValidationFcn", @matlab.settings.mustBeLogicalScalar) ...
        ];
end
