classdef ContainerStatResponse < ebrains.dataproxy.JSONMapper
% ContainerStatResponse No description provided
% 
% ContainerStatResponse Properties:
%   name - type: string
%   objects_count - type: int32
%   bytes - type: int32
%   last_modified - type: string
%   is_public - type: logical
%   role - type: UserRole
%   is_initialized - type: logical

% This file is automatically generated using OpenAPI
% Specification version: 1.0.0
% MATLAB Generator for OpenAPI version: 1.0.9


    % Class properties
    properties
        % name - type: string
        name string { ebrains.dataproxy.JSONMapper.fieldName(name,"name") }
        % objects_count - type: int32
        objects_count int32 { ebrains.dataproxy.JSONMapper.fieldName(objects_count,"objects_count") }
        % bytes - type: int32
        bytes int32 { ebrains.dataproxy.JSONMapper.fieldName(bytes,"bytes") }
        % last_modified - type: string
        last_modified string { ebrains.dataproxy.JSONMapper.fieldName(last_modified,"last_modified") }
        % is_public - type: logical
        is_public logical { ebrains.dataproxy.JSONMapper.fieldName(is_public,"is_public") }
        % role - type: UserRole
        role  { ebrains.dataproxy.JSONMapper.fieldName(role,"role") }
        % is_initialized - type: logical
        is_initialized logical { ebrains.dataproxy.JSONMapper.fieldName(is_initialized,"is_initialized") }
    end

    % Class methods
    methods
        % Constructor
        function obj = ContainerStatResponse(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { ebrains.dataproxy.JSONMapper.ConstructorArgument } = []
                inputs.?ebrains.dataproxy.models.ContainerStatResponse
            end
            obj@ebrains.dataproxy.JSONMapper(s,inputs);
        end
    end %methods
end %class

