classdef HTTPValidationError < ebrains.dataproxy.JSONMapper
% HTTPValidationError No description provided
% 
% HTTPValidationError Properties:
%   detail - type: array of ValidationError

% This file is automatically generated using OpenAPI
% Specification version: 1.0.0
% MATLAB Generator for OpenAPI version: 1.0.9


    % Class properties
    properties
        % detail - type: array of ValidationError
        detail ebrains.dataproxy.models.ValidationError { ebrains.dataproxy.JSONMapper.fieldName(detail,"detail"), ebrains.dataproxy.JSONMapper.JSONArray }
    end

    % Class methods
    methods
        % Constructor
        function obj = HTTPValidationError(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { ebrains.dataproxy.JSONMapper.ConstructorArgument } = []
                inputs.?ebrains.dataproxy.models.HTTPValidationError
            end
            obj@ebrains.dataproxy.JSONMapper(s,inputs);
        end
    end %methods
end %class

