classdef PermalinkModel < ebrains.dataproxy.JSONMapper
% PermalinkModel No description provided
% 
% PermalinkModel Properties:
%   entity_id - type: string
%   bucket_name - type: string
%   object_name - type: string
%   description - type: string
%   created_at - type: datetime
%   last_accessed_at - type: datetime
%   issuer - type: string
%   revoked - type: logical

% This file is automatically generated using OpenAPI
% Specification version: 1.0.0
% MATLAB Generator for OpenAPI version: 1.0.9


    % Class properties
    properties
        % entity_id - type: string
        entity_id string { ebrains.dataproxy.JSONMapper.fieldName(entity_id,"entity_id") }
        % bucket_name - type: string
        bucket_name string { ebrains.dataproxy.JSONMapper.fieldName(bucket_name,"bucket_name") }
        % object_name - type: string
        object_name string { ebrains.dataproxy.JSONMapper.fieldName(object_name,"object_name") }
        % description - type: string
        description string { ebrains.dataproxy.JSONMapper.fieldName(description,"description") }
        % created_at - type: datetime
        created_at datetime { ebrains.dataproxy.JSONMapper.stringDatetime(created_at,'yyyy-MM-dd''T''HH:mm:ss.SSSZ', 'TimeZone', 'local'), ebrains.dataproxy.JSONMapper.fieldName(created_at,"created_at") }
        % last_accessed_at - type: datetime
        last_accessed_at datetime { ebrains.dataproxy.JSONMapper.stringDatetime(last_accessed_at,'yyyy-MM-dd''T''HH:mm:ss.SSSZ', 'TimeZone', 'local'), ebrains.dataproxy.JSONMapper.fieldName(last_accessed_at,"last_accessed_at") }
        % issuer - type: string
        issuer string { ebrains.dataproxy.JSONMapper.fieldName(issuer,"issuer") }
        % revoked - type: logical
        revoked logical { ebrains.dataproxy.JSONMapper.fieldName(revoked,"revoked") }
    end

    % Class methods
    methods
        % Constructor
        function obj = PermalinkModel(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { ebrains.dataproxy.JSONMapper.ConstructorArgument } = []
                inputs.?ebrains.dataproxy.models.PermalinkModel
            end
            obj@ebrains.dataproxy.JSONMapper(s,inputs);
        end
    end %methods
end %class

