classdef RenameObjectSetting < ebrains.dataproxy.JSONMapper
% RenameObjectSetting No description provided
% 
% RenameObjectSetting Properties:
%   target_name - type: string

% This file is automatically generated using OpenAPI
% Specification version: 1.0.0
% MATLAB Generator for OpenAPI version: 1.0.9


    % Class properties
    properties
        % target_name - type: string
        target_name string { ebrains.dataproxy.JSONMapper.fieldName(target_name,"target_name") }
    end

    % Class methods
    methods
        % Constructor
        function obj = RenameObjectSetting(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { ebrains.dataproxy.JSONMapper.ConstructorArgument } = []
                inputs.?ebrains.dataproxy.models.RenameObjectSetting
            end
            obj@ebrains.dataproxy.JSONMapper(s,inputs);
        end
    end %methods
end %class

