classdef GetDataSizeLabelTest < matlab.unittest.TestCase
    % GetDataSizeLabelTest - Unit tests for ebrains.util.getDataSizeLabel

    properties (TestParameter)
        SizeCase = struct(...
            'Zero',     {{0, '0.00 bytes'}}, ...
            'Bytes',    {{1, '1.00 bytes'}}, ...
            'SubKb',    {{999, '999.00 bytes'}}, ...
            'Kilobyte', {{1e3, '1.00 kB'}}, ...
            'Megabyte', {{1e6, '1.00 MB'}}, ...
            'Gigabyte', {{1e9, '1.00 GB'}}, ...
            'Terabyte', {{1e12, '1.00 TB'}}, ...
            'Petabyte', {{1e15, '1.00 PB'}}, ...
            'BeyondPetabyte', {{1e18, '1000.00 PB'}} ...
            )
    end

    methods (Test)
        function testFormatsSizeWithUnit(testCase, SizeCase)
            sizeInBytes = SizeCase{1};
            expectedLabel = SizeCase{2};

            actual = ebrains.util.getDataSizeLabel(sizeInBytes);

            testCase.verifyEqual(actual, expectedLabel);
        end

        function testRejectsNegativeSize(testCase)
            testCase.verifyError(@() ebrains.util.getDataSizeLabel(-1), ...
                'MATLAB:validators:mustBeNonnegative');
        end

        function testRejectsInfiniteSize(testCase)
            testCase.verifyError(@() ebrains.util.getDataSizeLabel(Inf), ...
                'MATLAB:validators:mustBeFinite');
        end
    end
end
