classdef GraphEntity < ebrains.kgcore.JSONMapper
% GraphEntity No description provided
% 
% GraphEntity Properties:
%   id - type: string
%   types - type: array of string
%   name - type: string
%   space - type: string
%   inbound - type: array of GraphEntity
%   outbound - type: array of GraphEntity

% This file is automatically generated using OpenAPI
% Specification version: 1.0.0
% MATLAB Generator for OpenAPI version: 1.0.9


    % Class properties
    properties
        % id - type: string
        id string { ebrains.kgcore.JSONMapper.fieldName(id,"id") }
        % types - type: array of string
        types string { ebrains.kgcore.JSONMapper.fieldName(types,"types"), ebrains.kgcore.JSONMapper.JSONArray }
        % name - type: string
        name string { ebrains.kgcore.JSONMapper.fieldName(name,"name") }
        % space - type: string
        space string { ebrains.kgcore.JSONMapper.fieldName(space,"space") }
        % inbound - type: array of GraphEntity
        inbound ebrains.kgcore.models.GraphEntity { ebrains.kgcore.JSONMapper.fieldName(inbound,"inbound"), ebrains.kgcore.JSONMapper.JSONArray }
        % outbound - type: array of GraphEntity
        outbound ebrains.kgcore.models.GraphEntity { ebrains.kgcore.JSONMapper.fieldName(outbound,"outbound"), ebrains.kgcore.JSONMapper.JSONArray }
    end

    % Class methods
    methods
        % Constructor
        function obj = GraphEntity(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { ebrains.kgcore.JSONMapper.ConstructorArgument } = []
                inputs.?ebrains.kgcore.models.GraphEntity
            end
            obj@ebrains.kgcore.JSONMapper(s,inputs);
        end
    end %methods
end %class

