classdef PaginatedStreamResultJsonLdDoc_data < ebrains.kgcore.JSONMapper
% PaginatedStreamResultJsonLdDoc_data No description provided
% 
% PaginatedStreamResultJsonLdDoc_data Properties:
%   parallel - type: logical

% This file is automatically generated using OpenAPI
% Specification version: 1.0.0
% MATLAB Generator for OpenAPI version: 1.0.9


    % Class properties
    properties
        % parallel - type: logical
        parallel logical { ebrains.kgcore.JSONMapper.fieldName(parallel,"parallel") }
    end

    % Class methods
    methods
        % Constructor
        function obj = PaginatedStreamResultJsonLdDoc_data(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { ebrains.kgcore.JSONMapper.ConstructorArgument } = []
                inputs.?ebrains.kgcore.models.PaginatedStreamResultJsonLdDoc_data
            end
            obj@ebrains.kgcore.JSONMapper(s,inputs);
        end
    end %methods
end %class

