classdef SpaceName < ebrains.kgcore.JSONMapper
% SpaceName No description provided
% 
% SpaceName Properties:
%   name - type: string
%   wildcard - type: logical

% This file is automatically generated using OpenAPI
% Specification version: 1.0.0
% MATLAB Generator for OpenAPI version: 1.0.9


    % Class properties
    properties
        % name - type: string
        name string { ebrains.kgcore.JSONMapper.fieldName(name,"name") }
        % wildcard - type: logical
        wildcard logical { ebrains.kgcore.JSONMapper.fieldName(wildcard,"wildcard") }
    end

    % Class methods
    methods
        % Constructor
        function obj = SpaceName(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { ebrains.kgcore.JSONMapper.ConstructorArgument } = []
                inputs.?ebrains.kgcore.models.SpaceName
            end
            obj@ebrains.kgcore.JSONMapper(s,inputs);
        end
    end %methods
end %class

