classdef AclAccessType < ebrains.dataproxy.JSONEnum
% AclAccessType An enumeration.

    % This file is automatically generated using OpenAPI
    % Specification version: 1.0.0
    % MATLAB Generator for OpenAPI version: 1.0.9
    

    properties  (Constant)
        baseType = "string"
    end

    enumeration 
        read ("read")
        write ("write")
    end

end %class

