classdef ContainerStat < ebrains.dataproxy.JSONMapper
% ContainerStat No description provided
% 
% ContainerStat Properties:
%   name - type: string
%   objects_count - type: int32
%   bytes - type: int32
%   last_modified - type: string

% This file is automatically generated using OpenAPI
% Specification version: 1.0.0
% MATLAB Generator for OpenAPI version: 1.0.9


    % Class properties
    properties
        % name - type: string
        name string { ebrains.dataproxy.JSONMapper.fieldName(name,"name") }
        % objects_count - type: int32
        objects_count int32 { ebrains.dataproxy.JSONMapper.fieldName(objects_count,"objects_count") }
        % bytes - type: int32
        bytes int32 { ebrains.dataproxy.JSONMapper.fieldName(bytes,"bytes") }
        % last_modified - type: string
        last_modified string { ebrains.dataproxy.JSONMapper.fieldName(last_modified,"last_modified") }
    end

    % Class methods
    methods
        % Constructor
        function obj = ContainerStat(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { ebrains.dataproxy.JSONMapper.ConstructorArgument } = []
                inputs.?ebrains.dataproxy.models.ContainerStat
            end
            obj@ebrains.dataproxy.JSONMapper(s,inputs);
        end
    end %methods
end %class

