classdef DeleteResponse < ebrains.dataproxy.JSONMapper
% DeleteResponse No description provided
% 
% DeleteResponse Properties:
%   failures - type: array of string
%   number_of_removals - type: int32

% This file is automatically generated using OpenAPI
% Specification version: 1.0.0
% MATLAB Generator for OpenAPI version: 1.0.9


    % Class properties
    properties
        % failures - type: array of string
        failures string { ebrains.dataproxy.JSONMapper.fieldName(failures,"failures"), ebrains.dataproxy.JSONMapper.JSONArray }
        % number_of_removals - type: int32
        number_of_removals int32 { ebrains.dataproxy.JSONMapper.fieldName(number_of_removals,"number_of_removals") }
    end

    % Class methods
    methods
        % Constructor
        function obj = DeleteResponse(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { ebrains.dataproxy.JSONMapper.ConstructorArgument } = []
                inputs.?ebrains.dataproxy.models.DeleteResponse
            end
            obj@ebrains.dataproxy.JSONMapper(s,inputs);
        end
    end %methods
end %class

