classdef PermalinkUpdateForm < ebrains.dataproxy.JSONMapper
% PermalinkUpdateForm No description provided
% 
% PermalinkUpdateForm Properties:
%   object_name - type: string

% This file is automatically generated using OpenAPI
% Specification version: 1.0.0
% MATLAB Generator for OpenAPI version: 1.0.9


    % Class properties
    properties
        % object_name - type: string
        object_name string { ebrains.dataproxy.JSONMapper.fieldName(object_name,"object_name") }
    end

    % Class methods
    methods
        % Constructor
        function obj = PermalinkUpdateForm(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { ebrains.dataproxy.JSONMapper.ConstructorArgument } = []
                inputs.?ebrains.dataproxy.models.PermalinkUpdateForm
            end
            obj@ebrains.dataproxy.JSONMapper(s,inputs);
        end
    end %methods
end %class

