classdef IncomingLink < ebrains.kgcore.JSONMapper
% IncomingLink No description provided
% 
% IncomingLink Properties:
%   http__schema_org_identifier - type: string
%   https__core_kg_ebrains_eu_vocab_meta_sourceTypes - type: array of SourceType

% This file is automatically generated using OpenAPI
% Specification version: 1.0.0
% MATLAB Generator for OpenAPI version: 1.0.9


    % Class properties
    properties
        % http__schema_org_identifier - type: string
        http__schema_org_identifier string { ebrains.kgcore.JSONMapper.fieldName(http__schema_org_identifier,"http://schema.org/identifier") }
        % https__core_kg_ebrains_eu_vocab_meta_sourceTypes - type: array of SourceType
        https__core_kg_ebrains_eu_vocab_meta_sourceTypes ebrains.kgcore.models.SourceType { ebrains.kgcore.JSONMapper.fieldName(https__core_kg_ebrains_eu_vocab_meta_sourceTypes,"https://core.kg.ebrains.eu/vocab/meta/sourceTypes"), ebrains.kgcore.JSONMapper.JSONArray }
    end

    % Class methods
    methods
        % Constructor
        function obj = IncomingLink(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { ebrains.kgcore.JSONMapper.ConstructorArgument } = []
                inputs.?ebrains.kgcore.models.IncomingLink
            end
            obj@ebrains.kgcore.JSONMapper(s,inputs);
        end
    end %methods
end %class

