classdef PaginatedSuggestedLink < ebrains.kgcore.JSONMapper
% PaginatedSuggestedLink No description provided
% 
% PaginatedSuggestedLink Properties:
%   data - type: array of SuggestedLink
%   totalResults - type: int64
%   size - type: int64
%   from - type: int64

% This file is automatically generated using OpenAPI
% Specification version: 1.0.0
% MATLAB Generator for OpenAPI version: 1.0.9


    % Class properties
    properties
        % data - type: array of SuggestedLink
        data ebrains.kgcore.models.SuggestedLink { ebrains.kgcore.JSONMapper.fieldName(data,"data"), ebrains.kgcore.JSONMapper.JSONArray }
        % totalResults - type: int64
        totalResults int64 { ebrains.kgcore.JSONMapper.fieldName(totalResults,"totalResults") }
        % size - type: int64
        size int64 { ebrains.kgcore.JSONMapper.fieldName(size,"size") }
        % from - type: int64
        from int64 { ebrains.kgcore.JSONMapper.fieldName(from,"from") }
    end

    % Class methods
    methods
        % Constructor
        function obj = PaginatedSuggestedLink(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { ebrains.kgcore.JSONMapper.ConstructorArgument } = []
                inputs.?ebrains.kgcore.models.PaginatedSuggestedLink
            end
            obj@ebrains.kgcore.JSONMapper(s,inputs);
        end
    end %methods
end %class

