classdef ResultUser_data < ebrains.kgcore.JSONMapper
% ResultUser_data No description provided
% 
% ResultUser_data Properties:
%   givenName - type: string
%   familyName - type: string
%   userName - type: string
%   email - type: string
%   nativeId - type: string
%   displayName - type: string
%   id - type: JsonLdId
%   empty - type: logical

% This file is automatically generated using OpenAPI
% Specification version: 1.0.0
% MATLAB Generator for OpenAPI version: 1.0.9


    % Class properties
    properties
        % givenName - type: string
        givenName string { ebrains.kgcore.JSONMapper.fieldName(givenName,"givenName") }
        % familyName - type: string
        familyName string { ebrains.kgcore.JSONMapper.fieldName(familyName,"familyName") }
        % userName - type: string
        userName string { ebrains.kgcore.JSONMapper.fieldName(userName,"userName") }
        % email - type: string
        email string { ebrains.kgcore.JSONMapper.fieldName(email,"email") }
        % nativeId - type: string
        nativeId string { ebrains.kgcore.JSONMapper.fieldName(nativeId,"nativeId") }
        % displayName - type: string
        displayName string { ebrains.kgcore.JSONMapper.fieldName(displayName,"displayName") }
        % id - type: JsonLdId
        id ebrains.kgcore.models.JsonLdId { ebrains.kgcore.JSONMapper.fieldName(id,"id") }
        % empty - type: logical
        empty logical { ebrains.kgcore.JSONMapper.fieldName(empty,"empty") }
    end

    % Class methods
    methods
        % Constructor
        function obj = ResultUser_data(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { ebrains.kgcore.JSONMapper.ConstructorArgument } = []
                inputs.?ebrains.kgcore.models.ResultUser_data
            end
            obj@ebrains.kgcore.JSONMapper(s,inputs);
        end
    end %methods
end %class

