classdef SuggestedLink < ebrains.kgcore.JSONMapper
% SuggestedLink No description provided
% 
% SuggestedLink Properties:
%   id - type: string
%   label - type: string
%   type - type: string
%   space - type: string
%   additionalInformation - type: string

% This file is automatically generated using OpenAPI
% Specification version: 1.0.0
% MATLAB Generator for OpenAPI version: 1.0.9


    % Class properties
    properties
        % id - type: string
        id string { ebrains.kgcore.JSONMapper.fieldName(id,"id") }
        % label - type: string
        label string { ebrains.kgcore.JSONMapper.fieldName(label,"label") }
        % type - type: string
        type string { ebrains.kgcore.JSONMapper.fieldName(type,"type") }
        % space - type: string
        space string { ebrains.kgcore.JSONMapper.fieldName(space,"space") }
        % additionalInformation - type: string
        additionalInformation string { ebrains.kgcore.JSONMapper.fieldName(additionalInformation,"additionalInformation") }
    end

    % Class methods
    methods
        % Constructor
        function obj = SuggestedLink(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { ebrains.kgcore.JSONMapper.ConstructorArgument } = []
                inputs.?ebrains.kgcore.models.SuggestedLink
            end
            obj@ebrains.kgcore.JSONMapper(s,inputs);
        end
    end %methods
end %class

