classdef CollabSearchResult < ebrains.collaboratory.JSONMapper
% CollabSearchResult No description provided
% 
% CollabSearchResult Properties:
%   name - type: string
%   title - type: string
%   description - type: string
%   isPublic - type: logical
%   isMember - type: logical
%   hasDrive - type: logical
%   link - type: string
%   createDate - type: datetime
%   driveRepositoryId - type: string
%   nbLike - type: int32
%   owner - type: string

% This file is automatically generated using OpenAPI
% Specification version: 1.0
% MATLAB Generator for OpenAPI version: 1.0.9


    % Class properties
    properties
        % name - type: string
        name string { ebrains.collaboratory.JSONMapper.fieldName(name,"name") }
        % title - type: string
        title string { ebrains.collaboratory.JSONMapper.fieldName(title,"title") }
        % description - type: string
        description string { ebrains.collaboratory.JSONMapper.fieldName(description,"description") }
        % isPublic - type: logical
        isPublic logical { ebrains.collaboratory.JSONMapper.fieldName(isPublic,"isPublic") }
        % isMember - type: logical
        isMember logical { ebrains.collaboratory.JSONMapper.fieldName(isMember,"isMember") }
        % hasDrive - type: logical
        hasDrive logical { ebrains.collaboratory.JSONMapper.fieldName(hasDrive,"hasDrive") }
        % link - type: string
        link string { ebrains.collaboratory.JSONMapper.fieldName(link,"link") }
        % createDate - type: datetime
        createDate datetime { ebrains.collaboratory.JSONMapper.stringDatetime(createDate,'yyyy-MM-dd''T''HH:mm:ss.SSSZ', 'TimeZone', 'local'), ebrains.collaboratory.JSONMapper.fieldName(createDate,"createDate") }
        % driveRepositoryId - type: string
        driveRepositoryId string { ebrains.collaboratory.JSONMapper.fieldName(driveRepositoryId,"driveRepositoryId") }
        % nbLike - type: int32
        nbLike int32 { ebrains.collaboratory.JSONMapper.fieldName(nbLike,"nbLike") }
        % owner - type: string
        owner string { ebrains.collaboratory.JSONMapper.fieldName(owner,"owner") }
    end

    % Class methods
    methods
        % Constructor
        function obj = CollabSearchResult(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { ebrains.collaboratory.JSONMapper.ConstructorArgument } = []
                inputs.?ebrains.collaboratory.models.CollabSearchResult
            end
            obj@ebrains.collaboratory.JSONMapper(s,inputs);
        end
    end %methods
end %class

