classdef MembershipRequest < ebrains.collaboratory.JSONMapper
% MembershipRequest No description provided
% 
% MembershipRequest Properties:
%   username - type: string
%   target - type: string
%   status - type: string

% This file is automatically generated using OpenAPI
% Specification version: 1.0
% MATLAB Generator for OpenAPI version: 1.0.9


    % Class properties
    properties
        % username - type: string
        username string { ebrains.collaboratory.JSONMapper.fieldName(username,"username") }
        % target - type: string
        target string { ebrains.collaboratory.JSONMapper.fieldName(target,"target") }
        % status - type: string
        status  { ebrains.collaboratory.JSONMapper.fieldName(status,"status") }
    end

    % Class methods
    methods
        % Constructor
        function obj = MembershipRequest(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { ebrains.collaboratory.JSONMapper.ConstructorArgument } = []
                inputs.?ebrains.collaboratory.models.MembershipRequest
            end
            obj@ebrains.collaboratory.JSONMapper(s,inputs);
        end
    end %methods
end %class

