classdef MembershipRequestStatusEnum < ebrains.collaboratory.JSONEnum
% MembershipRequestStatusEnum No description provided

    % This file is automatically generated using OpenAPI
    % Specification version: 1.0
    % MATLAB Generator for OpenAPI version: 1.0.9
    

    properties  (Constant)
        baseType = ""
    end

    enumeration 
        pending ("pending")
        approved ("approved")
        rejected ("rejected")
    end

end %class

