classdef SwiftObject < ebrains.dataproxy.JSONMapper
% SwiftObject No description provided
% 
% SwiftObject Properties:
%   hash - type: string
%   last_modified - type: string
%   bytes - type: int32
%   name - type: string
%   content_type - type: string

% This file is automatically generated using OpenAPI
% Specification version: 1.0.0
% MATLAB Generator for OpenAPI version: 1.0.9


    % Class properties
    properties
        % hash - type: string
        hash string { ebrains.dataproxy.JSONMapper.fieldName(hash,"hash") }
        % last_modified - type: string
        last_modified string { ebrains.dataproxy.JSONMapper.fieldName(last_modified,"last_modified") }
        % bytes - type: int32
        bytes int32 { ebrains.dataproxy.JSONMapper.fieldName(bytes,"bytes") }
        % name - type: string
        name string { ebrains.dataproxy.JSONMapper.fieldName(name,"name") }
        % content_type - type: string
        content_type string { ebrains.dataproxy.JSONMapper.fieldName(content_type,"content_type") }
    end

    % Class methods
    methods
        % Constructor
        function obj = SwiftObject(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { ebrains.dataproxy.JSONMapper.ConstructorArgument } = []
                inputs.?ebrains.dataproxy.models.SwiftObject
            end
            obj@ebrains.dataproxy.JSONMapper(s,inputs);
        end
    end %methods
end %class

