classdef UserRole < ebrains.dataproxy.JSONEnum
% UserRole An enumeration.

    % This file is automatically generated using OpenAPI
    % Specification version: 1.0.0
    % MATLAB Generator for OpenAPI version: 1.0.9
    

    properties  (Constant)
        baseType = "string"
    end

    enumeration 
        administrator ("administrator")
        editor ("editor")
        viewer ("viewer")
    end

end %class

