classdef ValidationError < ebrains.dataproxy.JSONMapper
% ValidationError No description provided
% 
% ValidationError Properties:
%   loc - type: array of Location_inner
%   msg - type: string
%   type - type: string

% This file is automatically generated using OpenAPI
% Specification version: 1.0.0
% MATLAB Generator for OpenAPI version: 1.0.9


    % Class properties
    properties
        % loc - type: array of Location_inner
        loc ebrains.dataproxy.models.Location_inner { ebrains.dataproxy.JSONMapper.fieldName(loc,"loc"), ebrains.dataproxy.JSONMapper.JSONArray }
        % msg - type: string
        msg string { ebrains.dataproxy.JSONMapper.fieldName(msg,"msg") }
        % type - type: string
        type string { ebrains.dataproxy.JSONMapper.fieldName(type,"type") }
    end

    % Class methods
    methods
        % Constructor
        function obj = ValidationError(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { ebrains.dataproxy.JSONMapper.ConstructorArgument } = []
                inputs.?ebrains.dataproxy.models.ValidationError
            end
            obj@ebrains.dataproxy.JSONMapper(s,inputs);
        end
    end %methods
end %class

