classdef Error < ebrains.kgcore.JSONMapper
% Error No description provided
% 
% Error Properties:
%   code - type: int32
%   message - type: string
%   instanceId - type: string

% This file is automatically generated using OpenAPI
% Specification version: 1.0.0
% MATLAB Generator for OpenAPI version: 1.0.9


    % Class properties
    properties
        % code - type: int32
        code int32 { ebrains.kgcore.JSONMapper.fieldName(code,"code") }
        % message - type: string
        message string { ebrains.kgcore.JSONMapper.fieldName(message,"message") }
        % instanceId - type: string
        instanceId string { ebrains.kgcore.JSONMapper.fieldName(instanceId,"instanceId") }
    end

    % Class methods
    methods
        % Constructor
        function obj = Error(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { ebrains.kgcore.JSONMapper.ConstructorArgument } = []
                inputs.?ebrains.kgcore.models.Error
            end
            obj@ebrains.kgcore.JSONMapper(s,inputs);
        end
    end %methods
end %class

