classdef InstanceId < ebrains.kgcore.JSONMapper
% InstanceId No description provided
% 
% InstanceId Properties:
%   uuid - type: string
%   space - type: SpaceName
%   unresolved - type: logical

% This file is automatically generated using OpenAPI
% Specification version: 1.0.0
% MATLAB Generator for OpenAPI version: 1.0.9


    % Class properties
    properties
        % uuid - type: string
        uuid string { ebrains.kgcore.JSONMapper.fieldName(uuid,"uuid") }
        % space - type: SpaceName
        space ebrains.kgcore.models.SpaceName { ebrains.kgcore.JSONMapper.fieldName(space,"space") }
        % unresolved - type: logical
        unresolved logical { ebrains.kgcore.JSONMapper.fieldName(unresolved,"unresolved") }
    end

    % Class methods
    methods
        % Constructor
        function obj = InstanceId(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { ebrains.kgcore.JSONMapper.ConstructorArgument } = []
                inputs.?ebrains.kgcore.models.InstanceId
            end
            obj@ebrains.kgcore.JSONMapper(s,inputs);
        end
    end %methods
end %class

