classdef ResultReleaseStatusDataEnum < ebrains.kgcore.JSONEnum
% ResultReleaseStatusDataEnum No description provided

    % This file is automatically generated using OpenAPI
    % Specification version: 1.0.0
    % MATLAB Generator for OpenAPI version: 1.0.9
    

    properties  (Constant)
        baseType = ""
    end

    enumeration 
        RELEASED ("RELEASED")
        UNRELEASED ("UNRELEASED")
        HAS_CHANGED ("HAS_CHANGED")
    end

end %class

