classdef TargetType < ebrains.kgcore.JSONMapper
% TargetType No description provided
% 
% TargetType Properties:
%   https__core_kg_ebrains_eu_vocab_meta_occurrences - type: int32
%   https__core_kg_ebrains_eu_vocab_meta_spaces - type: array of SpaceReference
%   https__core_kg_ebrains_eu_vocab_meta_type - type: string

% This file is automatically generated using OpenAPI
% Specification version: 1.0.0
% MATLAB Generator for OpenAPI version: 1.0.9


    % Class properties
    properties
        % https__core_kg_ebrains_eu_vocab_meta_occurrences - type: int32
        https__core_kg_ebrains_eu_vocab_meta_occurrences int32 { ebrains.kgcore.JSONMapper.fieldName(https__core_kg_ebrains_eu_vocab_meta_occurrences,"https://core.kg.ebrains.eu/vocab/meta/occurrences") }
        % https__core_kg_ebrains_eu_vocab_meta_spaces - type: array of SpaceReference
        https__core_kg_ebrains_eu_vocab_meta_spaces ebrains.kgcore.models.SpaceReference { ebrains.kgcore.JSONMapper.fieldName(https__core_kg_ebrains_eu_vocab_meta_spaces,"https://core.kg.ebrains.eu/vocab/meta/spaces"), ebrains.kgcore.JSONMapper.JSONArray }
        % https__core_kg_ebrains_eu_vocab_meta_type - type: string
        https__core_kg_ebrains_eu_vocab_meta_type string { ebrains.kgcore.JSONMapper.fieldName(https__core_kg_ebrains_eu_vocab_meta_type,"https://core.kg.ebrains.eu/vocab/meta/type") }
    end

    % Class methods
    methods
        % Constructor
        function obj = TargetType(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { ebrains.kgcore.JSONMapper.ConstructorArgument } = []
                inputs.?ebrains.kgcore.models.TargetType
            end
            obj@ebrains.kgcore.JSONMapper(s,inputs);
        end
    end %methods
end %class

