name: Prepare toolbox release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Matches tags like v1.2.3
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number in major.minor.patch format'
        required: true
        type: string

jobs:
  prepare-release:
    name: Prepare toolbox release
    uses: ehennestad/matbox-actions/.github/workflows/prepare-release-workflow.yml@v1
    with:
      # Do not change
      version: ${{ inputs.version }}
      
      # Do not change
      ref_name: ${{ github.ref_name }}
      
      # Path to directory containing source code. This directory will be packaged
      # into the toolbox. Important: This should not be a namespace directory
      source_directory: src
      
      # Path to directory containing tests. This directory will be used for 
      # locating MATLAB  test suites
      tests_directory: tests

      # Path to directory containing tools and MLToolboxInfo.json. Used for finding
      # unit tests, running customized MatBox tasks, and determining toolbox metadata
      tools_directory: tools
    secrets:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
