name: Test code

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '*md'
      - '.github/**'

  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '*md'
      - '.github/**'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-code:
    name: Analyse and test code
    uses: ehennestad/matbox-actions/.github/workflows/test-code-workflow.yml@v1
    with:
      matlab_release: latest
      matlab_use_cache: true
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
