classdef CollabForm < ebrains.collaboratory.JSONMapper
% CollabForm No description provided
% 
% CollabForm Properties:
%   name - type: string
%   title - type: string
%   description - type: string
%   drive - type: logical
%   chat - type: logical
%   public - type: logical

% This file is automatically generated using OpenAPI
% Specification version: 1.0
% MATLAB Generator for OpenAPI version: 1.0.9


    % Class properties
    properties
        % name - type: string
        name string { ebrains.collaboratory.JSONMapper.fieldName(name,"name") }
        % title - type: string
        title string { ebrains.collaboratory.JSONMapper.fieldName(title,"title") }
        % description - type: string
        description string { ebrains.collaboratory.JSONMapper.fieldName(description,"description") }
        % drive - type: logical
        drive logical { ebrains.collaboratory.JSONMapper.fieldName(drive,"drive") }
        % chat - type: logical
        chat logical { ebrains.collaboratory.JSONMapper.fieldName(chat,"chat") }
        % public - type: logical
        public logical { ebrains.collaboratory.JSONMapper.fieldName(public,"public") }
    end

    % Class methods
    methods
        % Constructor
        function obj = CollabForm(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { ebrains.collaboratory.JSONMapper.ConstructorArgument } = []
                inputs.?ebrains.collaboratory.models.CollabForm
            end
            obj@ebrains.collaboratory.JSONMapper(s,inputs);
        end
    end %methods
end %class

