classdef EbrainsClientRepresentationItem < ebrains.collaboratory.JSONMapper
% EbrainsClientRepresentationItem No description provided
% 
% EbrainsClientRepresentationItem Properties:
%   clientId - type: string
%   owner - type: string
%   maintainers - type: array of string
%   accessDeniedToGuests - type: logical
%   featureAuthenticate - type: logical
%   featureAuthenticateIntValue - type: int32
%   guestPropertyIntValue - type: int32

% This file is automatically generated using OpenAPI
% Specification version: 1.0
% MATLAB Generator for OpenAPI version: 1.0.9


    % Class properties
    properties
        % clientId - type: string
        clientId string { ebrains.collaboratory.JSONMapper.fieldName(clientId,"clientId") }
        % owner - type: string
        owner string { ebrains.collaboratory.JSONMapper.fieldName(owner,"owner") }
        % maintainers - type: array of string
        maintainers string { ebrains.collaboratory.JSONMapper.fieldName(maintainers,"maintainers"), ebrains.collaboratory.JSONMapper.JSONArray }
        % accessDeniedToGuests - type: logical
        accessDeniedToGuests logical { ebrains.collaboratory.JSONMapper.fieldName(accessDeniedToGuests,"accessDeniedToGuests") }
        % featureAuthenticate - type: logical
        featureAuthenticate logical { ebrains.collaboratory.JSONMapper.fieldName(featureAuthenticate,"featureAuthenticate") }
        % featureAuthenticateIntValue - type: int32
        featureAuthenticateIntValue int32 { ebrains.collaboratory.JSONMapper.fieldName(featureAuthenticateIntValue,"featureAuthenticateIntValue") }
        % guestPropertyIntValue - type: int32
        guestPropertyIntValue int32 { ebrains.collaboratory.JSONMapper.fieldName(guestPropertyIntValue,"guestPropertyIntValue") }
    end

    % Class methods
    methods
        % Constructor
        function obj = EbrainsClientRepresentationItem(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { ebrains.collaboratory.JSONMapper.ConstructorArgument } = []
                inputs.?ebrains.collaboratory.models.EbrainsClientRepresentationItem
            end
            obj@ebrains.collaboratory.JSONMapper(s,inputs);
        end
    end %methods
end %class

