classdef Email < ebrains.collaboratory.JSONMapper
% Email No description provided
% 
% Email Properties:
%   emailSubject - type: string
%   emailContent - type: string

% This file is automatically generated using OpenAPI
% Specification version: 1.0
% MATLAB Generator for OpenAPI version: 1.0.9


    % Class properties
    properties
        % emailSubject - type: string
        emailSubject string { ebrains.collaboratory.JSONMapper.fieldName(emailSubject,"emailSubject") }
        % emailContent - type: string
        emailContent string { ebrains.collaboratory.JSONMapper.fieldName(emailContent,"emailContent") }
    end

    % Class methods
    methods
        % Constructor
        function obj = Email(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { ebrains.collaboratory.JSONMapper.ConstructorArgument } = []
                inputs.?ebrains.collaboratory.models.Email
            end
            obj@ebrains.collaboratory.JSONMapper(s,inputs);
        end
    end %methods
end %class

